typography_spectrum: 0.31710366741754115
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.41308173653669655
  lightness: 0.751576274400577
  saturation: 0.9505864228121936
  rhythmicContrast: 0.10614601639099419
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8293602468911558
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andrés
  email: arguapacha@acm.org
  url: 'http://www.arguapacha.com'
name: Yawner Corner
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/30a6e2a1-9992-44ec-bec7-ee622e82e6d2.ico
title: The Yawner Corner
content: []
description: Bothered with Boredom
purpose: []
url: 'http://yawner.arguapacha.com/'
