typography_spectrum: 0.31710366741754115
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.41308173653669655
  lightness: 0.751576274400577
  saturation: 0.9505864228121936
  rhythmicContrast: 0.10614601639099419
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8293602468911558
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andrés
  email: arguapacha@acm.org
  url: www.arguapacha.com
name: arguapacha
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Yawner Corner
content: []
description: Bothered with Boredom
purpose: []
url: 'https://thegrid.ai/yawner-corner'
